[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
